project:
  type: website

website:
  title: "Professor Gabriel Ramos"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "T\u00e9cnicas de Estudo"
        href: tecnicas-de-estudo.qmd
      - text: Ferramentas
        href: ferramentas.qmd
      - text: Blog
        href: blog.qmd
      - text: Contato
        href: contato.qmd
format:
  html:
    theme: cosmo
    toc: true
